#ifndef ALLSENSORS_288FEAT_H
#define ALLSENSORS_288FEAT_H

#include <Arduino.h>

#include "sensor_features.h"

void compute_features(int16_t *IMU1_AccelX, int16_t *IMU1_AccelY, int16_t *IMU1_AccelZ, int16_t *IMU1_GyroX, int16_t *IMU1_GyroY, int16_t *IMU1_GyroZ, int16_t *IMU2_AccelX, int16_t *IMU2_AccelY, int16_t *IMU2_AccelZ, int16_t *IMU2_GyroX, int16_t *IMU2_GyroY, int16_t *IMU2_GyroZ, int16_t *IMU3_AccelX, int16_t *IMU3_AccelY, int16_t *IMU3_AccelZ, int16_t *IMU3_GyroX, int16_t *IMU3_GyroY, int16_t *IMU3_GyroZ, int16_t *Micro, float feature_vector[288]);

void compute_features(int16_t *IMU1_AccelX, int16_t *IMU1_AccelY, int16_t *IMU1_AccelZ, int16_t *IMU1_GyroX, int16_t *IMU1_GyroY, int16_t *IMU1_GyroZ, int16_t *IMU2_AccelX, int16_t *IMU2_AccelY, int16_t *IMU2_AccelZ, int16_t *IMU2_GyroX, int16_t *IMU2_GyroY, int16_t *IMU2_GyroZ, int16_t *IMU3_AccelX, int16_t *IMU3_AccelY, int16_t *IMU3_AccelZ, int16_t *IMU3_GyroX, int16_t *IMU3_GyroY, int16_t *IMU3_GyroZ, int16_t *Micro, float feature_vector[288]) {

    float IMU1_GyroMagnitude[99];
    compute_magnitude(IMU1_GyroX, IMU1_GyroY, IMU1_GyroZ, IMU1_GyroMagnitude, 99);
    float IMU3_GyroMagnitude[99];
    compute_magnitude(IMU3_GyroX, IMU3_GyroY, IMU3_GyroZ, IMU3_GyroMagnitude, 99);
    float IMU2_GyroMagnitude[99];
    compute_magnitude(IMU2_GyroX, IMU2_GyroY, IMU2_GyroZ, IMU2_GyroMagnitude, 99);
    float IMU1_AccelMagnitude[99];
    compute_magnitude(IMU1_AccelX, IMU1_AccelY, IMU1_AccelZ, IMU1_AccelMagnitude, 99);
    float IMU2_AccelMagnitude[99];
    compute_magnitude(IMU2_AccelX, IMU2_AccelY, IMU2_AccelZ, IMU2_AccelMagnitude, 99);
    float IMU3_AccelMagnitude[99];
    compute_magnitude(IMU3_AccelX, IMU3_AccelY, IMU3_AccelZ, IMU3_AccelMagnitude, 99);
    float IMU1_Pitch[99];
    compute_pitch(IMU1_AccelX, IMU1_AccelY, IMU1_AccelZ, IMU1_Pitch, 99);
    float IMU3_Pitch[99];
    compute_pitch(IMU3_AccelX, IMU3_AccelY, IMU3_AccelZ, IMU3_Pitch, 99);
    float IMU2_Pitch[99];
    compute_pitch(IMU2_AccelX, IMU2_AccelY, IMU2_AccelZ, IMU2_Pitch, 99);
    float IMU3_Roll[99];
    compute_roll(IMU3_AccelX, IMU3_AccelY, IMU3_AccelZ, IMU3_Roll, 99);
    float IMU2_Roll[99];
    compute_roll(IMU2_AccelX, IMU2_AccelY, IMU2_AccelZ, IMU2_Roll, 99);
    float IMU1_Roll[99];
    compute_roll(IMU1_AccelX, IMU1_AccelY, IMU1_AccelZ, IMU1_Roll, 99);
    feature_vector[0] = compute_minimum_float(IMU1_Pitch, 99);
    feature_vector[1] = compute_minimum(IMU1_AccelX, 99);
    feature_vector[2] = compute_median_float(IMU1_GyroMagnitude, 99);
    feature_vector[3] = compute_minimum_float(IMU3_Roll, 99);
    feature_vector[4] = compute_sumvalues(IMU1_AccelX, 99);
    feature_vector[5] = compute_sumvalues_float(IMU1_Pitch, 99);
    feature_vector[6] = compute_maximum(IMU3_AccelY, 99);
    feature_vector[7] = compute_mean(IMU1_AccelX, 99);
    feature_vector[8] = compute_mean_float(IMU1_Pitch, 99);
    feature_vector[9] = compute_sumvalues(IMU3_AccelY, 99);
    feature_vector[10] = compute_mean(IMU3_AccelY, 99);
    feature_vector[11] = compute_median(IMU3_AccelY, 99);
    feature_vector[12] = compute_median_float(IMU1_Pitch, 99);
    feature_vector[13] = compute_median_float(IMU1_AccelMagnitude, 99);
    feature_vector[14] = compute_median(IMU1_AccelX, 99);
    feature_vector[15] = compute_sumvalues_float(IMU3_Roll, 99);
    feature_vector[16] = compute_median_float(IMU3_Roll, 99);
    feature_vector[17] = compute_mean_float(IMU3_Roll, 99);
    feature_vector[18] = compute_minimum_float(IMU1_AccelMagnitude, 99);
    feature_vector[19] = compute_median(IMU2_GyroY, 99);
    feature_vector[20] = compute_mean_float(IMU1_GyroMagnitude, 99);
    feature_vector[21] = compute_maximum_float(IMU3_Pitch, 99);
    feature_vector[22] = compute_standarddeviation_float(IMU2_AccelMagnitude, 99);
    feature_vector[23] = compute_variance_float(IMU2_AccelMagnitude, 99);
    feature_vector[24] = compute_absolutemaximum_float(IMU3_Pitch, 99);
    feature_vector[25] = compute_rootmeansquare(IMU1_GyroX, 99);
    feature_vector[26] = compute_variance(IMU2_AccelX, 99);
    feature_vector[27] = compute_standarddeviation(IMU2_AccelX, 99);
    feature_vector[28] = compute_sumvalues(IMU2_GyroY, 99);
    feature_vector[29] = compute_sumvalues_float(IMU1_GyroMagnitude, 99);
    feature_vector[30] = compute_sumvalues_float(IMU2_Roll, 99);
    feature_vector[31] = compute_variance(IMU1_AccelX, 99);
    feature_vector[32] = compute_standarddeviation(IMU1_AccelX, 99);
    feature_vector[33] = compute_minimum_float(IMU1_Roll, 99);
    feature_vector[34] = compute_variance_float(IMU1_Pitch, 99);
    feature_vector[35] = compute_standarddeviation_float(IMU1_Pitch, 99);
    feature_vector[36] = compute_absolutemaximum(IMU3_AccelX, 99);
    feature_vector[37] = compute_minimum_float(IMU2_AccelMagnitude, 99);
    feature_vector[38] = compute_rootmeansquare(IMU2_GyroZ, 99);
    feature_vector[39] = compute_minimum(IMU1_AccelY, 99);
    feature_vector[40] = compute_rootmeansquare(IMU3_AccelX, 99);
    feature_vector[41] = compute_median(IMU1_GyroY, 99);
    feature_vector[42] = compute_rootmeansquare_float(IMU3_Pitch, 99);
    feature_vector[43] = compute_mean(IMU2_GyroY, 99);
    feature_vector[44] = compute_minimum(IMU2_AccelY, 99);
    feature_vector[45] = compute_rootmeansquare(IMU1_GyroY, 99);
    feature_vector[46] = compute_variance(IMU1_GyroX, 99);
    feature_vector[47] = compute_standarddeviation(IMU1_GyroX, 99);
    feature_vector[48] = compute_maximum(IMU3_AccelX, 99);
    feature_vector[49] = compute_absolutemaximum(IMU1_AccelZ, 99);
    feature_vector[50] = compute_mean_float(IMU2_Roll, 99);
    feature_vector[51] = compute_absolutemaximum_float(IMU2_Pitch, 99);
    feature_vector[52] = compute_minimum_float(IMU2_Pitch, 99);
    feature_vector[53] = compute_variance_float(IMU2_Pitch, 99);
    feature_vector[54] = compute_standarddeviation_float(IMU2_Pitch, 99);
    feature_vector[55] = compute_minimum(IMU2_AccelX, 99);
    feature_vector[56] = compute_maximum(IMU1_GyroX, 99);
    feature_vector[57] = compute_maximum(IMU3_AccelZ, 99);
    feature_vector[58] = compute_rootmeansquare_float(IMU1_GyroMagnitude, 99);
    feature_vector[59] = compute_maximum_float(IMU2_AccelMagnitude, 99);
    feature_vector[60] = compute_absolutemaximum_float(IMU2_AccelMagnitude, 99);
    feature_vector[61] = compute_sumvalues(IMU2_AccelY, 99);
    feature_vector[62] = compute_absolutemaximum(IMU2_AccelX, 99);
    feature_vector[63] = compute_minimum(IMU1_GyroX, 99);
    feature_vector[64] = compute_minimum_float(IMU2_Roll, 99);
    feature_vector[65] = compute_variance(IMU2_AccelZ, 99);
    feature_vector[66] = compute_standarddeviation(IMU2_AccelZ, 99);
    feature_vector[67] = compute_mean_float(IMU3_Pitch, 99);
    feature_vector[68] = compute_variance_float(IMU1_AccelMagnitude, 99);
    feature_vector[69] = compute_standarddeviation_float(IMU1_AccelMagnitude, 99);
    feature_vector[70] = compute_maximum(IMU2_GyroY, 99);
    feature_vector[71] = compute_mean(IMU3_AccelX, 99);
    feature_vector[72] = compute_median(IMU2_AccelY, 99);
    feature_vector[73] = compute_median_float(IMU3_Pitch, 99);
    feature_vector[74] = compute_absolutemaximum(IMU1_GyroX, 99);
    feature_vector[75] = compute_median(IMU3_AccelX, 99);
    feature_vector[76] = compute_mean(IMU2_AccelY, 99);
    feature_vector[77] = compute_median_float(IMU2_Roll, 99);
    feature_vector[78] = compute_median(IMU1_GyroZ, 99);
    feature_vector[79] = compute_median_float(IMU3_GyroMagnitude, 99);
    feature_vector[80] = compute_minimum(IMU2_GyroZ, 99);
    feature_vector[81] = compute_variance_float(IMU3_Pitch, 99);
    feature_vector[82] = compute_standarddeviation_float(IMU3_Pitch, 99);
    feature_vector[83] = compute_standarddeviation(IMU2_GyroZ, 99);
    feature_vector[84] = compute_variance(IMU2_GyroZ, 99);
    feature_vector[85] = compute_standarddeviation(IMU3_AccelZ, 99);
    feature_vector[86] = compute_variance(IMU3_AccelZ, 99);
    feature_vector[87] = compute_sumvalues_float(IMU3_Pitch, 99);
    feature_vector[88] = compute_absolutemaximum(IMU2_GyroZ, 99);
    feature_vector[89] = compute_variance(IMU2_GyroY, 99);
    feature_vector[90] = compute_standarddeviation(IMU2_GyroY, 99);
    feature_vector[91] = compute_sumvalues(IMU3_AccelX, 99);
    feature_vector[92] = compute_maximum(IMU1_GyroZ, 99);
    feature_vector[93] = compute_maximum(IMU2_GyroZ, 99);
    feature_vector[94] = compute_variance(IMU1_AccelY, 99);
    feature_vector[95] = compute_standarddeviation(IMU1_AccelY, 99);
    feature_vector[96] = compute_sumvalues(IMU3_AccelZ, 99);
    feature_vector[97] = compute_mean(IMU3_AccelZ, 99);
    feature_vector[98] = compute_standarddeviation(IMU3_AccelX, 99);
    feature_vector[99] = compute_variance(IMU3_AccelX, 99);
    feature_vector[100] = compute_standarddeviation(IMU3_GyroY, 99);
    feature_vector[101] = compute_variance(IMU3_GyroY, 99);
    feature_vector[102] = compute_standarddeviation_float(IMU1_Roll, 99);
    feature_vector[103] = compute_variance_float(IMU1_Roll, 99);
    feature_vector[104] = compute_rootmeansquare(IMU3_AccelZ, 99);
    feature_vector[105] = compute_sumvalues_float(IMU1_Roll, 99);
    feature_vector[106] = compute_minimum(IMU2_AccelZ, 99);
    feature_vector[107] = compute_variance(IMU3_GyroZ, 99);
    feature_vector[108] = compute_standarddeviation(IMU3_GyroZ, 99);
    feature_vector[109] = compute_mean_float(IMU3_GyroMagnitude, 99);
    feature_vector[110] = compute_median_float(IMU1_Roll, 99);
    feature_vector[111] = compute_mean_float(IMU1_Roll, 99);
    feature_vector[112] = compute_median(IMU3_AccelZ, 99);
    feature_vector[113] = compute_standarddeviation(IMU1_GyroY, 99);
    feature_vector[114] = compute_variance(IMU1_GyroY, 99);
    feature_vector[115] = compute_standarddeviation(IMU1_GyroZ, 99);
    feature_vector[116] = compute_variance(IMU1_GyroZ, 99);
    feature_vector[117] = compute_mean_float(IMU1_AccelMagnitude, 99);
    feature_vector[118] = compute_maximum(IMU3_GyroZ, 99);
    feature_vector[119] = compute_mean_float(IMU2_GyroMagnitude, 99);
    feature_vector[120] = compute_sumvalues(IMU1_AccelY, 99);
    feature_vector[121] = compute_standarddeviation(IMU1_AccelZ, 99);
    feature_vector[122] = compute_variance(IMU1_AccelZ, 99);
    feature_vector[123] = compute_maximum(IMU1_GyroY, 99);
    feature_vector[124] = compute_sumvalues_float(IMU3_GyroMagnitude, 99);
    feature_vector[125] = compute_variance_float(IMU3_AccelMagnitude, 99);
    feature_vector[126] = compute_standarddeviation_float(IMU3_AccelMagnitude, 99);
    feature_vector[127] = compute_minimum(IMU3_GyroZ, 99);
    feature_vector[128] = compute_variance_float(IMU2_Roll, 99);
    feature_vector[129] = compute_standarddeviation_float(IMU2_Roll, 99);
    feature_vector[130] = compute_mean(IMU1_AccelY, 99);
    feature_vector[131] = compute_rootmeansquare(IMU2_AccelY, 99);
    feature_vector[132] = compute_absolutemaximum(IMU1_GyroY, 99);
    feature_vector[133] = compute_rootmeansquare(IMU3_GyroZ, 99);
    feature_vector[134] = compute_minimum(IMU1_GyroY, 99);
    feature_vector[135] = compute_median(IMU1_AccelY, 99);
    feature_vector[136] = compute_minimum(IMU3_GyroY, 99);
    feature_vector[137] = compute_median(IMU2_GyroZ, 99);
    feature_vector[138] = compute_rootmeansquare(IMU3_GyroY, 99);
    feature_vector[139] = compute_rootmeansquare(IMU2_AccelX, 99);
    feature_vector[140] = compute_sumvalues_float(IMU1_AccelMagnitude, 99);
    feature_vector[141] = compute_maximum(IMU3_GyroY, 99);
    feature_vector[142] = compute_sumvalues_float(IMU2_GyroMagnitude, 99);
    feature_vector[143] = compute_maximum(IMU1_AccelZ, 99);
    feature_vector[144] = compute_rootmeansquare_float(IMU2_GyroMagnitude, 99);
    feature_vector[145] = compute_rootmeansquare_float(IMU3_GyroMagnitude, 99);
    feature_vector[146] = compute_rootmeansquare_float(IMU2_Pitch, 99);
    feature_vector[147] = compute_median_float(IMU2_GyroMagnitude, 99);
    feature_vector[148] = compute_maximum(Micro, 99);
    feature_vector[149] = compute_absolutemaximum_float(IMU1_GyroMagnitude, 99);
    feature_vector[150] = compute_maximum_float(IMU1_GyroMagnitude, 99);
    feature_vector[151] = compute_minimum(IMU2_GyroY, 99);
    feature_vector[152] = compute_minimum(IMU1_GyroZ, 99);
    feature_vector[153] = compute_variance_float(IMU1_GyroMagnitude, 99);
    feature_vector[154] = compute_standarddeviation_float(IMU1_GyroMagnitude, 99);
    feature_vector[155] = compute_mean(IMU1_GyroY, 99);
    feature_vector[156] = compute_sumvalues(IMU2_AccelX, 99);
    feature_vector[157] = compute_standarddeviation_float(IMU3_Roll, 99);
    feature_vector[158] = compute_variance_float(IMU3_Roll, 99);
    feature_vector[159] = compute_median_float(IMU2_Pitch, 99);
    feature_vector[160] = compute_absolutemaximum_float(IMU3_AccelMagnitude, 99);
    feature_vector[161] = compute_maximum_float(IMU3_AccelMagnitude, 99);
    feature_vector[162] = compute_mean(IMU2_AccelX, 99);
    feature_vector[163] = compute_absolutemaximum(IMU3_GyroY, 99);
    feature_vector[164] = compute_rootmeansquare(IMU1_GyroZ, 99);
    feature_vector[165] = compute_maximum_float(IMU1_AccelMagnitude, 99);
    feature_vector[166] = compute_absolutemaximum_float(IMU1_AccelMagnitude, 99);
    feature_vector[167] = compute_absolutemaximum(IMU2_GyroY, 99);
    feature_vector[168] = compute_mean_float(IMU2_Pitch, 99);
    feature_vector[169] = compute_minimum(IMU2_GyroX, 99);
    feature_vector[170] = compute_median(IMU2_AccelX, 99);
    feature_vector[171] = compute_absolutemaximum(IMU3_GyroZ, 99);
    feature_vector[172] = compute_standarddeviation(IMU2_AccelY, 99);
    feature_vector[173] = compute_variance(IMU2_AccelY, 99);
    feature_vector[174] = compute_rootmeansquare_float(IMU3_AccelMagnitude, 99);
    feature_vector[175] = compute_standarddeviation(IMU2_GyroX, 99);
    feature_vector[176] = compute_variance(IMU2_GyroX, 99);
    feature_vector[177] = compute_minimum_float(IMU3_AccelMagnitude, 99);
    feature_vector[178] = compute_sumvalues(IMU1_GyroY, 99);
    feature_vector[179] = compute_maximum(IMU3_GyroX, 99);
    feature_vector[180] = compute_sumvalues_float(IMU2_Pitch, 99);
    feature_vector[181] = compute_standarddeviation_float(IMU2_GyroMagnitude, 99);
    feature_vector[182] = compute_variance_float(IMU2_GyroMagnitude, 99);
    feature_vector[183] = compute_rootmeansquare(IMU2_GyroX, 99);
    feature_vector[184] = compute_rootmeansquare_float(IMU1_AccelMagnitude, 99);
    feature_vector[185] = compute_standarddeviation(IMU3_GyroX, 99);
    feature_vector[186] = compute_variance(IMU3_GyroX, 99);
    feature_vector[187] = compute_mean_float(IMU3_AccelMagnitude, 99);
    feature_vector[188] = compute_variance_float(IMU3_GyroMagnitude, 99);
    feature_vector[189] = compute_standarddeviation_float(IMU3_GyroMagnitude, 99);
    feature_vector[190] = compute_rootmeansquare(IMU3_GyroX, 99);
    feature_vector[191] = compute_absolutemaximum_float(IMU3_GyroMagnitude, 99);
    feature_vector[192] = compute_maximum_float(IMU3_GyroMagnitude, 99);
    feature_vector[193] = compute_absolutemaximum_float(IMU2_GyroMagnitude, 99);
    feature_vector[194] = compute_maximum_float(IMU2_GyroMagnitude, 99);
    feature_vector[195] = compute_absolutemaximum(IMU1_GyroZ, 99);
    feature_vector[196] = compute_absolutemaximum_float(IMU2_Roll, 99);
    feature_vector[197] = compute_sumvalues(IMU2_AccelZ, 99);
    feature_vector[198] = compute_minimum(IMU3_AccelY, 99);
    feature_vector[199] = compute_minimum(IMU3_GyroX, 99);
    feature_vector[200] = compute_rootmeansquare(IMU2_GyroY, 99);
    feature_vector[201] = compute_maximum(IMU2_GyroX, 99);
    feature_vector[202] = compute_maximum(IMU2_AccelX, 99);
    feature_vector[203] = compute_standarddeviation(IMU3_AccelY, 99);
    feature_vector[204] = compute_variance(IMU3_AccelY, 99);
    feature_vector[205] = compute_absolutemaximum(IMU3_GyroX, 99);
    feature_vector[206] = compute_mean(IMU2_AccelZ, 99);
    feature_vector[207] = compute_maximum_float(IMU1_Pitch, 99);
    feature_vector[208] = compute_minimum_float(IMU3_GyroMagnitude, 99);
    feature_vector[209] = compute_mean(IMU2_GyroZ, 99);
    feature_vector[210] = compute_rootmeansquare(IMU1_AccelX, 99);
    feature_vector[211] = compute_sumvalues(IMU1_GyroZ, 99);
    feature_vector[212] = compute_sumvalues_float(IMU3_AccelMagnitude, 99);
    feature_vector[213] = compute_absolutemaximum(IMU2_GyroX, 99);
    feature_vector[214] = compute_median(IMU2_AccelZ, 99);
    feature_vector[215] = compute_median(IMU3_GyroY, 99);
    feature_vector[216] = compute_maximum(IMU1_AccelX, 99);
    feature_vector[217] = compute_maximum_float(IMU2_Roll, 99);
    feature_vector[218] = compute_rootmeansquare_float(IMU1_Pitch, 99);
    feature_vector[219] = compute_mean(IMU1_GyroZ, 99);
    feature_vector[220] = compute_sumvalues(IMU2_GyroZ, 99);
    feature_vector[221] = compute_absolutemaximum_float(IMU3_Roll, 99);
    feature_vector[222] = compute_rootmeansquare(IMU1_AccelZ, 99);
    feature_vector[223] = compute_rootmeansquare(IMU2_AccelZ, 99);
    feature_vector[224] = compute_sumvalues(IMU3_GyroY, 99);
    feature_vector[225] = compute_rootmeansquare(IMU3_AccelY, 99);
    feature_vector[226] = compute_absolutemaximum(IMU1_AccelY, 99);
    feature_vector[227] = compute_minimum_float(IMU3_Pitch, 99);
    feature_vector[228] = compute_median_float(IMU2_AccelMagnitude, 99);
    feature_vector[229] = compute_mean(IMU3_GyroY, 99);
    feature_vector[230] = compute_minimum(IMU3_AccelX, 99);
    feature_vector[231] = compute_median_float(IMU3_AccelMagnitude, 99);
    feature_vector[232] = compute_absolutemaximum_float(IMU1_Roll, 99);
    feature_vector[233] = compute_absolutemaximum(IMU2_AccelZ, 99);
    feature_vector[234] = compute_maximum_float(IMU3_Roll, 99);
    feature_vector[235] = compute_minimum(IMU1_AccelZ, 99);
    feature_vector[236] = compute_minimum(Micro, 99);
    feature_vector[237] = compute_median(IMU2_GyroX, 99);
    feature_vector[238] = compute_median(IMU1_AccelZ, 99);
    feature_vector[239] = compute_standarddeviation(Micro, 99);
    feature_vector[240] = compute_variance(Micro, 99);
    feature_vector[241] = compute_mean(IMU1_AccelZ, 99);
    feature_vector[242] = compute_sumvalues(IMU1_AccelZ, 99);
    feature_vector[243] = compute_maximum_float(IMU1_Roll, 99);
    feature_vector[244] = compute_absolutemaximum(IMU3_AccelZ, 99);
    feature_vector[245] = compute_rootmeansquare(Micro, 99);
    feature_vector[246] = compute_minimum(IMU3_AccelZ, 99);
    feature_vector[247] = compute_median(Micro, 99);
    feature_vector[248] = compute_minimum_float(IMU2_GyroMagnitude, 99);
    feature_vector[249] = compute_absolutemaximum(IMU3_AccelY, 99);
    feature_vector[250] = compute_sumvalues(IMU2_GyroX, 99);
    feature_vector[251] = compute_rootmeansquare_float(IMU2_AccelMagnitude, 99);
    feature_vector[252] = 99;
    feature_vector[253] = 99;
    feature_vector[254] = 99;
    feature_vector[255] = 99;
    feature_vector[256] = 99;
    feature_vector[257] = 99;
    feature_vector[258] = 99;
    feature_vector[259] = 99;
    feature_vector[260] = 99;
    feature_vector[261] = 99;
    feature_vector[262] = 99;
    feature_vector[263] = 99;
    feature_vector[264] = 99;
    feature_vector[265] = 99;
    feature_vector[266] = 99;
    feature_vector[267] = 99;
    feature_vector[268] = 99;
    feature_vector[269] = 99;
    feature_vector[270] = 99;
    feature_vector[271] = 99;
    feature_vector[272] = 99;
    feature_vector[273] = 99;
    feature_vector[274] = 99;
    feature_vector[275] = 99;
    feature_vector[276] = 99;
    feature_vector[277] = 99;
    feature_vector[278] = 99;
    feature_vector[279] = 99;
    feature_vector[280] = 99;
    feature_vector[281] = 99;
    feature_vector[282] = 99;
    feature_vector[283] = compute_maximum(IMU1_AccelY, 99);
    feature_vector[284] = compute_mean(IMU2_GyroX, 99);
    feature_vector[285] = compute_rootmeansquare_float(IMU3_Roll, 99);
    feature_vector[286] = compute_maximum_float(IMU2_Pitch, 99);
    feature_vector[287] = compute_maximum(IMU2_AccelZ, 99);
}

#endif  // ALLSENSORS_288FEAT_H
